version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank_db
      environment:
      SECRET_KEY: "your_secret_key_value"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/bank_db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
 
volumes:
  postgres_data:
